apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jobz.server.fullname" . }}
  labels:
    {{- include "jobz.server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jobz.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jobz.server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jobz.server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.server.name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.server.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          env:
            - name: PORT
              value: {{ .Values.server.containerPort | quote }}
            - name: DATABASE_FILE_PATH
              value: "/var/sqlite/jobz.db"
          volumeMounts:
            - name: sqlite
              mountPath: /var/sqlite
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      volumes:
        - name: sqlite
          persistentVolumeClaim:
            claimName: {{ include "jobz.server.fullname" . }}
