apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jobz.server.serviceAccountName" . }}
  labels:
    {{- include "jobz.server.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
