name: Publish images to Docker Hub and Helm chart to GitHub Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: huan231/jobz:${{ env.VERSION }}

      - run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v3
        with:
          context: ./ui/
          file: ./ui/Dockerfile
          push: true
          tags: huan231/jobzui:${{ env.VERSION }}
          build-args: |
            COMMIT_HASH=${{ env.COMMIT_HASH }}

  publish-chart:
    runs-on: ubuntu-latest
    needs: publish-images

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v1
        with:
          version: v3.9.0

      - uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
