apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jobz.ui.fullname" . }}
  labels:
    {{- include "jobz.ui.labels" . | nindent 4 }}
data:
  API_BASE_URL: "http{{ if .Values.server.ingress.tls }}s{{ end }}://{{ .Values.server.ingress.host }}{{ .Values.server.ingress.path }}"
