apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jobz.ui.fullname" . }}
  labels:
    {{- include "jobz.ui.labels" . | nindent 4 }}
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ui.ingress.className }}
  {{- if .Values.ui.ingress.tls }}
  tls:
    {{ toYaml .Values.ui.ingress.tls | indent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ui.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ui.ingress.path }}
            pathType: {{ .Values.ui.ingress.pathType }}
            backend:
              service:
                name: {{ include "jobz.ui.fullname" . }}
                port:
                  number: {{ .Values.ui.service.port }}
